name: Build Plugin Release

on:
  release:
    types: [released]

permissions:
  contents: write  # This is required to upload release assets

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        uses: php-actions/composer@v2
        with:
          dev: no

      - name: Generate plugin artifact
        run: |
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/example-plugin.zip" .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/example-plugin.zip
          asset_name: example-plugin.zip
          asset_content_type: application/zip