name: Build Plugin Release

on:
  release:
    types: [released]

permissions:
  contents: write  # Required to upload release assets

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest

    env:
      RELEASE_DIR: ${{ github.workspace }}/release
      ARTIFACT_NAME: updatesync-example.zip
      ARTIFACT_PATH: ${{ github.workspace }}/updatesync-example.zip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --prefer-dist --no-progress --no-interaction

      - name: Generate Plugin Artifact
        run: |
          set -e
          mkdir -p "$RELEASE_DIR"
          rsync -rc --exclude-from="${{ github.workspace }}/.distignore" "${{ github.workspace }}/" "$RELEASE_DIR/" --delete --delete-excluded
          
          cd "$RELEASE_DIR" || exit 1
          zip -r "$ARTIFACT_PATH" .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
